name: Auto Build
on: [workflow_call]

concurrency: 
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build WSA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
        root: [magisk, none]
        gapps: [MindTheGapps, none]
        release: [retail]
        compress-format: [7z]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y whiptail setools lzip wine patchelf e2fsprogs python3-pip aria2 p7zip-full attr xz-utils unzip cabextract
          sudo wget -P /usr/local/bin/ https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
          sudo chmod +x /usr/local/bin/winetricks
          wget -P /home/runner/.cache/winetricks/msxml6/ https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}/wine/.cache/winetricks/msxml6/msxml6-KB973686-enu-amd64.exe
          pip list --disable-pip-version-check | grep -E "^requests " >/dev/null 2>&1 || python3 -m pip install requests
          winetricks list-installed | grep -E "^msxml6" >/dev/null 2>&1 || winetricks msxml6 || abort

      - name: Grant executable permission
        run: chmod +x ./scripts/build.sh

      - name: Build WSA GAPPS ${{ matrix.root }} ${{ matrix.arch }}
        id: wsa
        run: ./scripts/build.sh --arch ${{ matrix.arch }} --release-type ${{ matrix.release }} --magisk-ver stable --gapps-brand ${{ matrix.gapps }} --root-sol ${{ matrix.root }} --remove-amazon --compress-format ${{ matrix.compress-format }}

      - name: Prepare release tag
        id: date
        run: |
          echo "date=$(date +'v%Y-%m-%d')" >> $GITHUB_OUTPUT
          cd ./output/
          echo "checksum=$(sha256sum '${{ steps.wsa.outputs.artifact }}.${{ matrix.compress-format }}')" >> $GITHUB_OUTPUT

      - name: Update build to release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./output/${{ steps.wsa.outputs.artifact }}.${{ matrix.compress-format }}
          fail_on_unmatched_files: true
          append_body: true
          tag_name: ${{ steps.date.outputs.date }}
          body: ${{ steps.date.outputs.checksum }}
          
          
